# Generated by Django 4.0.3 on 2022-04-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_tag_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=255),
        ),
    ]
